parameters:
  core.handler.user.class: CoreBundle\Handler\UserHandler
  core.entity.user.class: CoreBundle\Entity\User
  core.service.user.class: CoreBundle\Service\User\UserService
services:
  core.handler.user:
    class: '%core.handler.user.class%'
    arguments:
      - '@core.service.user'
  core.service.user:
    class: '%core.service.user.class%'
    arguments:
      - '@service_container'
      - "@security.password_encoder"
      - '@templating'
      - '@mailer'
      - '%sender_email%'