api_user:
  resource: '@ApiBundle/Controller/UserController.php'
  type: rest
  prefix: /api
  defaults:
    _format: json
api_check_phone:
  resource: '@ApiBundle/Controller/CheckPhoneController.php'
  type: rest
  prefix: /api
  defaults:
    _format: json